# Generated by Django 3.2.5 on 2021-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210915_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='highlighted',
        ),
    ]
