# Generated by Django 3.2.5 on 2021-09-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_remove_article_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner',
        ),
    ]
